name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Run cargo clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Check for build errors
      run: cargo check --workspace
    - name: Build
      run: cargo build --verbose
